apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.92.222.102.13.nip.io"
        - "events.92.222.102.13.nip.io"
        - "uptime.92.222.102.13.nip.io"
