apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-5rpm
plugin: rate-limiting
config:
  minute: 5
  policy: local
  fault_tolerant: true
  hide_client_headers: false
