apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.44.0
    helm:
      valuesObject:
        ingressController:
          enabled: true
          installCRDs: false
        proxy:
          type: LoadBalancer
          http:
            enabled: true
            containerPort: 8000
            servicePort: 80
          tls:
            enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          database: "off"
          proxy_access_log: /dev/stdout
          admin_access_log: /dev/stdout
          proxy_error_log: /dev/stderr
          admin_error_log: /dev/stderr
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
